// Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	  http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.


package com.amazonaws.serverless.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;


@DynamoDBTable(tableName = "Book")
public class Book implements Serializable {

    private static final long serialVersionUID = -8243145429438016232L;
    public static final String TITLE_INDEX = "Title-Index";

    public static final String AUTHOR_INDEX = "Author-Index";

    @DynamoDBHashKey
    private String BookId;

    @DynamoDBAttribute
    private String content;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = AUTHOR_INDEX)
    private String author;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = TITLE_INDEX)
    private String title;

    public Book() { }

    public Book(String bookId) {
        this.BookId = bookId;
    }

    public Book(String content,String author, String title) {
        this.content = content;
        this.author = author;
        this.title = title;
    }


    @DynamoDBHashKey(attributeName = "BookId")
    @DynamoDBAutoGeneratedKey
    public String getBookId() {
        return BookId;
    }

    @DynamoDBHashKey(attributeName = "BookId")
    @DynamoDBAutoGeneratedKey
    public void setBookId(String BookId) {
        this.BookId = BookId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String sport) {
        this.content = sport;
    }


    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


}
